In [1]:
import pandas as pd
import numpy as np
from py_files import fetch_data
%matplotlib inline

In [2]:
df = fetch_data.get_df()
df.columns = ['BellaLuna','Phoenix10', 'SeaSpray', 'WindDrift']

In [4]:
melted_df = df.T.reset_index().melt(id_vars = 'index')
melted_df.columns = ['Unit', 'Date', 'Sales']
melted_df

         Unit        Date     Sales
0   BellaLuna  2022-01-01      0.00
1   Phoenix10  2022-01-01      0.00
2    SeaSpray  2022-01-01      0.00
3   WindDrift  2022-01-01      0.00
4   BellaLuna  2022-02-01      0.00
5   Phoenix10  2022-02-01      0.00
6    SeaSpray  2022-02-01      0.00
7   WindDrift  2022-02-01      0.00
8   BellaLuna  2022-03-01      0.00
9   Phoenix10  2022-03-01   1179.24
10   SeaSpray  2022-03-01   2465.28
11  WindDrift  2022-03-01   4681.64
12  BellaLuna  2022-04-01      0.00
13  Phoenix10  2022-04-01   1447.60
14   SeaSpray  2022-04-01   2126.23
15  WindDrift  2022-04-01   4676.78
16  BellaLuna  2022-05-01      0.00
17  Phoenix10  2022-05-01   4157.06
18   SeaSpray  2022-05-01   5231.55
19  WindDrift  2022-05-01   6792.35
20  BellaLuna  2022-06-01      0.00
21  Phoenix10  2022-06-01   4482.64
22   SeaSpray  2022-06-01   7323.64
23  WindDrift  2022-06-01   7715.62
24  BellaLuna  2022-07-01   6494.46
25  Phoenix10  2022-07-01  10278.60
26   SeaSpray  2022-07-01   7532.66
27  WindDrift  2022-07-01   8782.68
28  BellaLuna  2022-08-01   7117.60
29  Phoenix10  2022-08-01  14964.72
30   SeaSpray  2022-08-01   6261.17
31  WindDrift  2022-08-01   4501.97
32  BellaLuna  2022-09-01   3634.40
33  Phoenix10  2022-09-01   5069.00
34   SeaSpray  2022-09-01      0.00
35  WindDrift  2022-09-01   4864.64
36  BellaLuna  2022-10-01    925.00
37  Phoenix10  2022-10-01   4576.33
38   SeaSpray  2022-10-01   1089.49
39  WindDrift  2022-10-01   2656.82
40  BellaLuna  2022-11-01      0.00
41  Phoenix10  2022-11-01   3684.61
42   SeaSpray  2022-11-01      0.00
43  WindDrift  2022-11-01      0.00
44  BellaLuna  2022-12-01      0.00
45  Phoenix10  2022-12-01    558.60
46   SeaSpray  2022-12-01   3600.00
47  WindDrift  2022-12-01      0.00

In [5]:
melted_df.to_excel("../data/processed/melted_sales.xlsx")